ALTER TABLE exam
    ADD COLUMN date DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN start_time TIME NOT NULL DEFAULT '09:00',
    ADD COLUMN end_time TIME NOT NULL DEFAULT '11:00';

ALTER TABLE exam ALTER COLUMN date DROP DEFAULT;
ALTER TABLE exam ALTER COLUMN start_time DROP DEFAULT;
ALTER TABLE exam ALTER COLUMN end_time DROP DEFAULT;

ALTER TABLE exam ADD CONSTRAINT chk_exam_time_range CHECK (start_time < end_time);